language: python

python:
  - "2.7"

sudo: false
cache:
  pip: true

install:
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install -r dev-requirements.txt

script:
  - "PYTHONPATH=. py.test -vv test/"
